version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bmg_api
        ports:
            - '${APP_PORT}:${APP_PORT}'
        networks:
            - bmg_network
        restart: always

    db:
        image: 'postgres:14-alpine'
        container_name: bmg_db
        environment:
            - 'POSTGRES_USER=${DB_USER}'
            - 'POSTGRES_PASSWORD=${DB_PASS}'
            - 'POSTGRES_DB=${DB_NAME}'
        restart: always
        ports:
            - '5432:5432'

networks:
    bmg_network:
